# Generated by Django 5.0.2 on 2024-02-24 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_photosubmission_delete_formdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photosubmission',
            name='capture_datetime',
        ),
        migrations.AddField(
            model_name='photosubmission',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='photosubmission',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='photosubmission',
            name='time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='photosubmission',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='photosubmission',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos/'),
        ),
    ]
