# Generated by Django 5.0.2 on 2024-02-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_remove_photosubmission_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photosubmission',
            name='date',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='photosubmission',
            name='time',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
